For #2077 PM-1971 downgrade jackson libs to 2.15.4 version because of the aws batch dependency on a deprecated class that was removed in 2.16 java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/PropertyNamingStrategy$PascalCaseStrategy
to upgrade to a higher jackson version, pegasus aws batch needs to be upgraded to   work with new aws batch libraries